package arm.node;

@:access(armory.logicnode.LogicNode)@:keep class MoveEnemy extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _SetVariable_001 = new armory.logicnode.SetVariableNode(this);
		_SetVariable_001.preallocInputs(3);
		_SetVariable_001.preallocOutputs(1);
		var _PlayActionFrom_001 = new armory.logicnode.PlayActionFromNode(this);
		_PlayActionFrom_001.preallocInputs(9);
		_PlayActionFrom_001.preallocOutputs(2);
		var _Print = new armory.logicnode.PrintNode(this);
		_Print.preallocInputs(2);
		_Print.preallocOutputs(1);
		var _Branch = new armory.logicnode.BranchNode(this);
		_Branch.preallocInputs(2);
		_Branch.preallocOutputs(2);
		var _OnTimer_002 = new armory.logicnode.OnTimerNode(this);
		_OnTimer_002.preallocInputs(2);
		_OnTimer_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.10000000149011612), _OnTimer_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _OnTimer_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_OnTimer_002, _Branch, 0, 0);
		var _VolumeTrigger = new armory.logicnode.VolumeTriggerNode(this);
		_VolumeTrigger.property0 = "begin";
		_VolumeTrigger.preallocInputs(2);
		_VolumeTrigger.preallocOutputs(1);
		var _GetObjectChild_002 = new armory.logicnode.GetChildNode(this);
		_GetObjectChild_002.property0 = "By Name";
		_GetObjectChild_002.preallocInputs(2);
		_GetObjectChild_002.preallocOutputs(1);
		var _SelfObject_001 = new armory.logicnode.SelfNode(this);
		_SelfObject_001.preallocInputs(0);
		_SelfObject_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_SelfObject_001, _GetObjectChild_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "triggerFrenteEnemigo"), _GetObjectChild_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectChild_002, _VolumeTrigger, 0, 0);
		var _GetObjectbyName = new armory.logicnode.GetObjectNode(this);
		_GetObjectbyName.preallocInputs(1);
		_GetObjectbyName.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "Trigger_animaciones_enemigos"), _GetObjectbyName, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectbyName, _VolumeTrigger, 0, 1);
		armory.logicnode.LogicNode.addLink(_VolumeTrigger, _Branch, 0, 1);
		armory.logicnode.LogicNode.addLink(_Branch, _Print, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "TRIGGER ENTER"), _Print, 0, 1);
		armory.logicnode.LogicNode.addLink(_Print, _PlayActionFrom_001, 0, 0);
		var _Object_002 = new armory.logicnode.ObjectNode(this);
		_Object_002.preallocInputs(1);
		_Object_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _Object_002, 0, 0);
		armory.logicnode.LogicNode.addLink(_Object_002, _PlayActionFrom_001, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "CicloCaminataManosArribaEnemigoPrincipal_rigging enemigo princi"), _PlayActionFrom_001, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 1), _PlayActionFrom_001, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 24), _PlayActionFrom_001, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.5), _PlayActionFrom_001, 0, 5);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 1.0), _PlayActionFrom_001, 0, 6);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _PlayActionFrom_001, 0, 7);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _PlayActionFrom_001, 0, 8);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom_001, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom_001, _SetVariable_001, 0, 0);
		var _Vector_004 = new armory.logicnode.VectorNode(this);
		_Vector_004.preallocInputs(3);
		_Vector_004.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.05000000074505806), _Vector_004, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_004, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_004, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_004, _SetVariable_001, 0, 1);
		var _Vector_005 = new armory.logicnode.VectorNode(this);
		_Vector_005.preallocInputs(3);
		_Vector_005.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.05999999865889549), _Vector_005, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_005, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_005, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_005, _SetVariable_001, 0, 2);
		armory.logicnode.LogicNode.addLink(_SetVariable_001, new armory.logicnode.NullNode(this), 0, 0);
		var _CallNodeGroup_001_Armorygroup_SetObjectLocation = new armory.logicnode.SetLocationNode(this);
		_CallNodeGroup_001_Armorygroup_SetObjectLocation.preallocInputs(4);
		_CallNodeGroup_001_Armorygroup_SetObjectLocation.preallocOutputs(1);
		var _CallNodeGroup_001_Armorygroup_GroupInputNode = new armory.logicnode.GroupInputsNode(this);
		_CallNodeGroup_001_Armorygroup_GroupInputNode.preallocInputs(0);
		_CallNodeGroup_001_Armorygroup_GroupInputNode.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_CallNodeGroup_001_Armorygroup_GroupInputNode, _CallNodeGroup_001_Armorygroup_SetObjectLocation, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _CallNodeGroup_001_Armorygroup_SetObjectLocation, 0, 1);
		var _CallNodeGroup_001_Armorygroup_VectorMath = new armory.logicnode.VectorMathNode(this);
		_CallNodeGroup_001_Armorygroup_VectorMath.property0 = "Add";
		_CallNodeGroup_001_Armorygroup_VectorMath.property1 = false;
		_CallNodeGroup_001_Armorygroup_VectorMath.preallocInputs(2);
		_CallNodeGroup_001_Armorygroup_VectorMath.preallocOutputs(1);
		var _CallNodeGroup_001_Armorygroup_GetObjectLocation = new armory.logicnode.GetLocationNode(this);
		_CallNodeGroup_001_Armorygroup_GetObjectLocation.preallocInputs(2);
		_CallNodeGroup_001_Armorygroup_GetObjectLocation.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _CallNodeGroup_001_Armorygroup_GetObjectLocation, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _CallNodeGroup_001_Armorygroup_GetObjectLocation, 0, 1);
		armory.logicnode.LogicNode.addLink(_CallNodeGroup_001_Armorygroup_GetObjectLocation, _CallNodeGroup_001_Armorygroup_VectorMath, 0, 0);
		armory.logicnode.LogicNode.addLink(_CallNodeGroup_001_Armorygroup_GroupInputNode, _CallNodeGroup_001_Armorygroup_VectorMath, 1, 1);
		armory.logicnode.LogicNode.addLink(_CallNodeGroup_001_Armorygroup_VectorMath, _CallNodeGroup_001_Armorygroup_SetObjectLocation, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _CallNodeGroup_001_Armorygroup_SetObjectLocation, 0, 3);
		armory.logicnode.LogicNode.addLink(_CallNodeGroup_001_Armorygroup_SetObjectLocation, new armory.logicnode.NullNode(this), 0, 0);
		var _CallNodeGroup_001_Armorygroup_GroupOutputNode = new armory.logicnode.GroupOutputsNode(this);
		_CallNodeGroup_001_Armorygroup_GroupOutputNode.preallocInputs(1);
		_CallNodeGroup_001_Armorygroup_GroupOutputNode.preallocOutputs(0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.NullNode(this), _CallNodeGroup_001_Armorygroup_GroupOutputNode, 0, 0);
		var _VerificarRotacion_VerificarRotacion_VerificarRotacion = new armory.logicnode.GroupOutputsNode(this);
		_VerificarRotacion_VerificarRotacion_VerificarRotacion.preallocInputs(2);
		_VerificarRotacion_VerificarRotacion_VerificarRotacion.preallocOutputs(0);
		var _VerificarRotacion_VerificarRotacion_Branch = new armory.logicnode.BranchNode(this);
		_VerificarRotacion_VerificarRotacion_Branch.preallocInputs(2);
		_VerificarRotacion_VerificarRotacion_Branch.preallocOutputs(2);
		var _VerificarRotacion_VerificarRotacion_GroupInputNode = new armory.logicnode.GroupInputsNode(this);
		_VerificarRotacion_VerificarRotacion_GroupInputNode.preallocInputs(0);
		_VerificarRotacion_VerificarRotacion_GroupInputNode.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_VerificarRotacion_VerificarRotacion_GroupInputNode, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_VerificarRotacion_VerificarRotacion_GroupInputNode, _VerificarRotacion_VerificarRotacion_Branch, 0, 0);
		var _VerificarRotacion_VerificarRotacion_Compare = new armory.logicnode.CompareNode(this);
		_VerificarRotacion_VerificarRotacion_Compare.property0 = "Greater Equal";
		_VerificarRotacion_VerificarRotacion_Compare.property1 = 9.999999747378752e-05;
		_VerificarRotacion_VerificarRotacion_Compare.preallocInputs(2);
		_VerificarRotacion_VerificarRotacion_Compare.preallocOutputs(1);
		var _VerificarRotacion_VerificarRotacion_GetObjectRotation = new armory.logicnode.GetRotationNode(this);
		_VerificarRotacion_VerificarRotacion_GetObjectRotation.property0 = "Global";
		_VerificarRotacion_VerificarRotacion_GetObjectRotation.preallocInputs(1);
		_VerificarRotacion_VerificarRotacion_GetObjectRotation.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _VerificarRotacion_VerificarRotacion_GetObjectRotation, 0, 0);
		armory.logicnode.LogicNode.addLink(_VerificarRotacion_VerificarRotacion_GetObjectRotation, _VerificarRotacion_VerificarRotacion_Compare, 0, 0);
		var _VerificarRotacion_VerificarRotacion_Rotation = new armory.logicnode.RotationNode(this);
		_VerificarRotacion_VerificarRotacion_Rotation.property0 = "EulerAngles";
		_VerificarRotacion_VerificarRotacion_Rotation.property1 = "Rad";
		_VerificarRotacion_VerificarRotacion_Rotation.property2 = "XYZ";
		_VerificarRotacion_VerificarRotacion_Rotation.preallocInputs(2);
		_VerificarRotacion_VerificarRotacion_Rotation.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.VectorNode(this, 0.0,0.0,180.0), _VerificarRotacion_VerificarRotacion_Rotation, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _VerificarRotacion_VerificarRotacion_Rotation, 0, 1);
		armory.logicnode.LogicNode.addLink(_VerificarRotacion_VerificarRotacion_Rotation, _VerificarRotacion_VerificarRotacion_Compare, 0, 1);
		armory.logicnode.LogicNode.addLink(_VerificarRotacion_VerificarRotacion_Compare, _VerificarRotacion_VerificarRotacion_Branch, 0, 1);
		armory.logicnode.LogicNode.addLink(_VerificarRotacion_VerificarRotacion_Branch, _VerificarRotacion_VerificarRotacion_VerificarRotacion, 0, 0);
		armory.logicnode.LogicNode.addLink(_VerificarRotacion_VerificarRotacion_Branch, _VerificarRotacion_VerificarRotacion_VerificarRotacion, 1, 1);
		var _OnUpdate = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate.property0 = "Update";
		_OnUpdate.preallocInputs(0);
		_OnUpdate.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate, _VerificarRotacion_VerificarRotacion_GroupInputNode, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.NullNode(this), _VerificarRotacion_VerificarRotacion_GroupInputNode, 0, 1);
		armory.logicnode.LogicNode.addLink(_VerificarRotacion_VerificarRotacion_VerificarRotacion, _CallNodeGroup_001_Armorygroup_GroupInputNode, 1, 0);
		var _VectorMath = new armory.logicnode.VectorMathNode(this);
		_VectorMath.property0 = "Multiply";
		_VectorMath.property1 = false;
		_VectorMath.preallocInputs(2);
		_VectorMath.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Vector_004, _VectorMath, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.VectorNode(this, -1.0,0.0,0.0), _VectorMath, 0, 1);
		armory.logicnode.LogicNode.addLink(_VectorMath, _CallNodeGroup_001_Armorygroup_GroupInputNode, 0, 1);
		armory.logicnode.LogicNode.addLink(_CallNodeGroup_001_Armorygroup_GroupOutputNode, new armory.logicnode.NullNode(this), 0, 0);
		var _SetVariable = new armory.logicnode.SetVariableNode(this);
		_SetVariable.preallocInputs(3);
		_SetVariable.preallocOutputs(1);
		var _PlayActionFrom_002 = new armory.logicnode.PlayActionFromNode(this);
		_PlayActionFrom_002.preallocInputs(9);
		_PlayActionFrom_002.preallocOutputs(2);
		var _Print_001 = new armory.logicnode.PrintNode(this);
		_Print_001.preallocInputs(2);
		_Print_001.preallocOutputs(1);
		var _Branch_001 = new armory.logicnode.BranchNode(this);
		_Branch_001.preallocInputs(2);
		_Branch_001.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Branch, _Branch_001, 1, 0);
		var _VolumeTrigger_001 = new armory.logicnode.VolumeTriggerNode(this);
		_VolumeTrigger_001.property0 = "end";
		_VolumeTrigger_001.preallocInputs(2);
		_VolumeTrigger_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetObjectChild_002, _VolumeTrigger_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectbyName, _VolumeTrigger_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_VolumeTrigger_001, _Branch_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_Branch_001, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Branch_001, _Print_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "TRIGGER  EXIT"), _Print_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_Print_001, _PlayActionFrom_002, 0, 0);
		armory.logicnode.LogicNode.addLink(_Object_002, _PlayActionFrom_002, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "CicloCaminataEnemigoPrincipal_rigging enemigo principal001"), _PlayActionFrom_002, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 1), _PlayActionFrom_002, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 24), _PlayActionFrom_002, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.5), _PlayActionFrom_002, 0, 5);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 1.0), _PlayActionFrom_002, 0, 6);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _PlayActionFrom_002, 0, 7);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _PlayActionFrom_002, 0, 8);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom_002, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom_002, _SetVariable, 0, 0);
		armory.logicnode.LogicNode.addLink(_Vector_004, _SetVariable, 0, 1);
		var _Vector_003 = new armory.logicnode.VectorNode(this);
		_Vector_003.preallocInputs(3);
		_Vector_003.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.05000000074505806), _Vector_003, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_003, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_003, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_003, _SetVariable, 0, 2);
		armory.logicnode.LogicNode.addLink(_SetVariable, new armory.logicnode.NullNode(this), 0, 0);
		var _PlayActionFrom_003 = new armory.logicnode.PlayActionFromNode(this);
		_PlayActionFrom_003.preallocInputs(9);
		_PlayActionFrom_003.preallocOutputs(2);
		var _SetVariable_004 = new armory.logicnode.SetVariableNode(this);
		_SetVariable_004.preallocInputs(3);
		_SetVariable_004.preallocOutputs(1);
		var _Branch_002 = new armory.logicnode.BranchNode(this);
		_Branch_002.preallocInputs(2);
		_Branch_002.preallocOutputs(2);
		var _OnTimer_001 = new armory.logicnode.OnTimerNode(this);
		_OnTimer_001.preallocInputs(2);
		_OnTimer_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.10000000149011612), _OnTimer_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _OnTimer_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_OnTimer_001, _Branch_002, 0, 0);
		var _VolumeTrigger_002 = new armory.logicnode.VolumeTriggerNode(this);
		_VolumeTrigger_002.property0 = "begin";
		_VolumeTrigger_002.preallocInputs(2);
		_VolumeTrigger_002.preallocOutputs(1);
		var _GetObjectChild_004 = new armory.logicnode.GetChildNode(this);
		_GetObjectChild_004.property0 = "By Name";
		_GetObjectChild_004.preallocInputs(2);
		_GetObjectChild_004.preallocOutputs(1);
		var _SelfObject_003 = new armory.logicnode.SelfNode(this);
		_SelfObject_003.preallocInputs(0);
		_SelfObject_003.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_SelfObject_003, _GetObjectChild_004, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "triggerFrenteEnemigo"), _GetObjectChild_004, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectChild_004, _VolumeTrigger_002, 0, 0);
		var _GetObjectbyName_001 = new armory.logicnode.GetObjectNode(this);
		_GetObjectbyName_001.preallocInputs(1);
		_GetObjectbyName_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "trigger_al_lado_personaje"), _GetObjectbyName_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectbyName_001, _VolumeTrigger_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_VolumeTrigger_002, _Branch_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_Branch_002, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Branch_002, _SetVariable_004, 0, 0);
		armory.logicnode.LogicNode.addLink(_Vector_004, _SetVariable_004, 0, 1);
		var _Vector_007 = new armory.logicnode.VectorNode(this);
		_Vector_007.preallocInputs(3);
		_Vector_007.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_007, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_007, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_007, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_007, _SetVariable_004, 0, 2);
		armory.logicnode.LogicNode.addLink(_SetVariable_004, _PlayActionFrom_003, 0, 0);
		armory.logicnode.LogicNode.addLink(_Object_002, _PlayActionFrom_003, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "abrazar_rigging enemigo principal001"), _PlayActionFrom_003, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 1), _PlayActionFrom_003, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 2), _PlayActionFrom_003, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.10000000149011612), _PlayActionFrom_003, 0, 5);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 2.0), _PlayActionFrom_003, 0, 6);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _PlayActionFrom_003, 0, 7);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _PlayActionFrom_003, 0, 8);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom_003, new armory.logicnode.NullNode(this), 0, 0);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom_003, new armory.logicnode.NullNode(this), 1, 0);
		var _AddObjecttoCollection = new armory.logicnode.AddObjectToGroupNode(this);
		_AddObjecttoCollection.preallocInputs(3);
		_AddObjecttoCollection.preallocOutputs(1);
		var _PlayActionFrom = new armory.logicnode.PlayActionFromNode(this);
		_PlayActionFrom.preallocInputs(9);
		_PlayActionFrom.preallocOutputs(2);
		var _SetVariable_003 = new armory.logicnode.SetVariableNode(this);
		_SetVariable_003.preallocInputs(3);
		_SetVariable_003.preallocOutputs(1);
		var _OnInit = new armory.logicnode.OnInitNode(this);
		_OnInit.preallocInputs(0);
		_OnInit.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnInit, _SetVariable_003, 0, 0);
		armory.logicnode.LogicNode.addLink(_Object_002, _SetVariable_003, 0, 1);
		var _GetObjectChild_001 = new armory.logicnode.GetChildNode(this);
		_GetObjectChild_001.property0 = "Contains";
		_GetObjectChild_001.preallocInputs(2);
		_GetObjectChild_001.preallocOutputs(1);
		var _SelfObject = new armory.logicnode.SelfNode(this);
		_SelfObject.preallocInputs(0);
		_SelfObject.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_SelfObject, _GetObjectChild_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "rigging enemigo principal"), _GetObjectChild_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectChild_001, _SetVariable_003, 0, 2);
		armory.logicnode.LogicNode.addLink(_SetVariable_003, _PlayActionFrom, 0, 0);
		armory.logicnode.LogicNode.addLink(_Object_002, _PlayActionFrom, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "CicloCaminataEnemigoPrincipal_rigging enemigo principal001"), _PlayActionFrom, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 0), _PlayActionFrom, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 23), _PlayActionFrom, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.25), _PlayActionFrom, 0, 5);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 1.0), _PlayActionFrom, 0, 6);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _PlayActionFrom, 0, 7);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _PlayActionFrom, 0, 8);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom, _AddObjecttoCollection, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "CollisionEnemigos"), _AddObjecttoCollection, 0, 1);
		var _GetObjectChild_003 = new armory.logicnode.GetChildNode(this);
		_GetObjectChild_003.property0 = "Contains";
		_GetObjectChild_003.preallocInputs(2);
		_GetObjectChild_003.preallocOutputs(1);
		var _SelfObject_002 = new armory.logicnode.SelfNode(this);
		_SelfObject_002.preallocInputs(0);
		_SelfObject_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_SelfObject_002, _GetObjectChild_003, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "triggerFrenteEnemigo"), _GetObjectChild_003, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectChild_003, _AddObjecttoCollection, 0, 2);
		armory.logicnode.LogicNode.addLink(_AddObjecttoCollection, new armory.logicnode.NullNode(this), 0, 0);
		var _OnContact = new armory.logicnode.OnContactNode(this);
		_OnContact.property0 = "begin";
		_OnContact.preallocInputs(2);
		_OnContact.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _OnContact, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _OnContact, 0, 1);
		armory.logicnode.LogicNode.addLink(_OnContact, new armory.logicnode.NullNode(this), 0, 0);
		var _OnTimer = new armory.logicnode.OnTimerNode(this);
		_OnTimer.preallocInputs(2);
		_OnTimer.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.10000000149011612), _OnTimer, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _OnTimer, 0, 1);
		armory.logicnode.LogicNode.addLink(_OnTimer, new armory.logicnode.NullNode(this), 0, 0);
		var _Print_003 = new armory.logicnode.PrintNode(this);
		_Print_003.preallocInputs(2);
		_Print_003.preallocOutputs(1);
		var _Print_002 = new armory.logicnode.PrintNode(this);
		_Print_002.preallocInputs(2);
		_Print_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.NullNode(this), _Print_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, ""), _Print_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_Print_002, _Print_003, 0, 0);
		var _GetObjectLocation = new armory.logicnode.GetLocationNode(this);
		_GetObjectLocation.preallocInputs(2);
		_GetObjectLocation.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectLocation, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _GetObjectLocation, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectLocation, _Print_003, 0, 1);
		armory.logicnode.LogicNode.addLink(_Print_003, new armory.logicnode.NullNode(this), 0, 0);
		var _ArrayLength_001 = new armory.logicnode.ArrayLengthNode(this);
		_ArrayLength_001.preallocInputs(1);
		_ArrayLength_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.NullNode(this), _ArrayLength_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLength_001, new armory.logicnode.IntegerNode(this, 0), 0, 0);
		var _PlayActionFrom_004 = new armory.logicnode.PlayActionFromNode(this);
		_PlayActionFrom_004.preallocInputs(9);
		_PlayActionFrom_004.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.NullNode(this), _PlayActionFrom_004, 0, 0);
		armory.logicnode.LogicNode.addLink(_Object_002, _PlayActionFrom_004, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "abrazar_rigging enemigo principal001"), _PlayActionFrom_004, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 1), _PlayActionFrom_004, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 2), _PlayActionFrom_004, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.10000000149011612), _PlayActionFrom_004, 0, 5);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 2.0), _PlayActionFrom_004, 0, 6);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _PlayActionFrom_004, 0, 7);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _PlayActionFrom_004, 0, 8);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom_004, new armory.logicnode.NullNode(this), 0, 0);
		armory.logicnode.LogicNode.addLink(_PlayActionFrom_004, new armory.logicnode.NullNode(this), 1, 0);
		var _Print_004 = new armory.logicnode.PrintNode(this);
		_Print_004.preallocInputs(2);
		_Print_004.preallocOutputs(1);
		var _Branch_003 = new armory.logicnode.BranchNode(this);
		_Branch_003.preallocInputs(2);
		_Branch_003.preallocOutputs(2);
		var _ArrayLoop = new armory.logicnode.ArrayLoopNode(this);
		_ArrayLoop.preallocInputs(2);
		_ArrayLoop.preallocOutputs(4);
		var _IsTrue = new armory.logicnode.IsTrueNode(this);
		_IsTrue.preallocInputs(2);
		_IsTrue.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.NullNode(this), _IsTrue, 0, 0);
		var _Compare = new armory.logicnode.CompareNode(this);
		_Compare.property0 = "Greater";
		_Compare.property1 = 9.999999747378752e-05;
		_Compare.preallocInputs(2);
		_Compare.preallocOutputs(1);
		var _ArrayLength = new armory.logicnode.ArrayLengthNode(this);
		_ArrayLength.preallocInputs(1);
		_ArrayLength.preallocOutputs(1);
		var _GetCollection = new armory.logicnode.GetGroupNode(this);
		_GetCollection.preallocInputs(1);
		_GetCollection.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "CollisionEnemigos"), _GetCollection, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetCollection, _ArrayLength, 0, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLength, _Compare, 0, 0);
		var _Integer = new armory.logicnode.IntegerNode(this);
		_Integer.preallocInputs(1);
		_Integer.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 0), _Integer, 0, 0);
		armory.logicnode.LogicNode.addLink(_Integer, _Compare, 0, 1);
		armory.logicnode.LogicNode.addLink(_Compare, _IsTrue, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue, _ArrayLoop, 0, 0);
		var _GetCollection_001 = new armory.logicnode.GetGroupNode(this);
		_GetCollection_001.preallocInputs(1);
		_GetCollection_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "CollisionEnemigos"), _GetCollection_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetCollection_001, _ArrayLoop, 0, 1);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, new armory.logicnode.IntegerNode(this, 0), 2, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, new armory.logicnode.NullNode(this), 3, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _Branch_003, 0, 0);
		var _VolumeTrigger_003 = new armory.logicnode.VolumeTriggerNode(this);
		_VolumeTrigger_003.property0 = "begin";
		_VolumeTrigger_003.preallocInputs(2);
		_VolumeTrigger_003.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _VolumeTrigger_003, 1, 0);
		var _GetObjectChild_005 = new armory.logicnode.GetChildNode(this);
		_GetObjectChild_005.property0 = "By Name";
		_GetObjectChild_005.preallocInputs(2);
		_GetObjectChild_005.preallocOutputs(1);
		var _SelfObject_004 = new armory.logicnode.SelfNode(this);
		_SelfObject_004.preallocInputs(0);
		_SelfObject_004.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_SelfObject_004, _GetObjectChild_005, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "triggerFrenteEnemigo"), _GetObjectChild_005, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectChild_005, _VolumeTrigger_003, 0, 1);
		armory.logicnode.LogicNode.addLink(_VolumeTrigger_003, _Branch_003, 0, 1);
		armory.logicnode.LogicNode.addLink(_Branch_003, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Branch_003, _Print_004, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "WORK!!!"), _Print_004, 0, 1);
		armory.logicnode.LogicNode.addLink(_Print_004, new armory.logicnode.NullNode(this), 0, 0);
		var _CallNodeGroup_Armorygroup_SetObjectLocation = new armory.logicnode.SetLocationNode(this);
		_CallNodeGroup_Armorygroup_SetObjectLocation.preallocInputs(4);
		_CallNodeGroup_Armorygroup_SetObjectLocation.preallocOutputs(1);
		var _CallNodeGroup_Armorygroup_GroupInputNode = new armory.logicnode.GroupInputsNode(this);
		_CallNodeGroup_Armorygroup_GroupInputNode.preallocInputs(0);
		_CallNodeGroup_Armorygroup_GroupInputNode.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_CallNodeGroup_Armorygroup_GroupInputNode, _CallNodeGroup_Armorygroup_SetObjectLocation, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _CallNodeGroup_Armorygroup_SetObjectLocation, 0, 1);
		var _CallNodeGroup_Armorygroup_VectorMath = new armory.logicnode.VectorMathNode(this);
		_CallNodeGroup_Armorygroup_VectorMath.property0 = "Add";
		_CallNodeGroup_Armorygroup_VectorMath.property1 = false;
		_CallNodeGroup_Armorygroup_VectorMath.preallocInputs(2);
		_CallNodeGroup_Armorygroup_VectorMath.preallocOutputs(1);
		var _CallNodeGroup_Armorygroup_GetObjectLocation = new armory.logicnode.GetLocationNode(this);
		_CallNodeGroup_Armorygroup_GetObjectLocation.preallocInputs(2);
		_CallNodeGroup_Armorygroup_GetObjectLocation.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _CallNodeGroup_Armorygroup_GetObjectLocation, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _CallNodeGroup_Armorygroup_GetObjectLocation, 0, 1);
		armory.logicnode.LogicNode.addLink(_CallNodeGroup_Armorygroup_GetObjectLocation, _CallNodeGroup_Armorygroup_VectorMath, 0, 0);
		armory.logicnode.LogicNode.addLink(_CallNodeGroup_Armorygroup_GroupInputNode, _CallNodeGroup_Armorygroup_VectorMath, 1, 1);
		armory.logicnode.LogicNode.addLink(_CallNodeGroup_Armorygroup_VectorMath, _CallNodeGroup_Armorygroup_SetObjectLocation, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _CallNodeGroup_Armorygroup_SetObjectLocation, 0, 3);
		armory.logicnode.LogicNode.addLink(_CallNodeGroup_Armorygroup_SetObjectLocation, new armory.logicnode.NullNode(this), 0, 0);
		var _CallNodeGroup_Armorygroup_GroupOutputNode = new armory.logicnode.GroupOutputsNode(this);
		_CallNodeGroup_Armorygroup_GroupOutputNode.preallocInputs(1);
		_CallNodeGroup_Armorygroup_GroupOutputNode.preallocOutputs(0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.NullNode(this), _CallNodeGroup_Armorygroup_GroupOutputNode, 0, 0);
		armory.logicnode.LogicNode.addLink(_VerificarRotacion_VerificarRotacion_VerificarRotacion, _CallNodeGroup_Armorygroup_GroupInputNode, 0, 0);
		armory.logicnode.LogicNode.addLink(_Vector_004, _CallNodeGroup_Armorygroup_GroupInputNode, 0, 1);
		armory.logicnode.LogicNode.addLink(_CallNodeGroup_Armorygroup_GroupOutputNode, new armory.logicnode.NullNode(this), 0, 0);
		var _SetVariable_005 = new armory.logicnode.SetVariableNode(this);
		_SetVariable_005.preallocInputs(3);
		_SetVariable_005.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.NullNode(this), _SetVariable_005, 0, 0);
		armory.logicnode.LogicNode.addLink(_Vector_004, _SetVariable_005, 0, 1);
		var _Vector_009 = new armory.logicnode.VectorNode(this);
		_Vector_009.preallocInputs(3);
		_Vector_009.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_009, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_009, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_009, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_009, _SetVariable_005, 0, 2);
		armory.logicnode.LogicNode.addLink(_SetVariable_005, new armory.logicnode.NullNode(this), 0, 0);
	}
}